	--- # create a directory and copy files over with different permissions and ownership
- hosts: snc-public
  gather_facts: no
  tasks: 

  - debug:
      var: service
  - name:  install service 
    yum:
      name: "{{ service }}"
      state: latest

  - name: create index.html file
    ansible.builtin.file:
      name: /var/www/html/index.html
      state: touch

  - name: add content to index file
    lineinfile: 
      line: "{{ ansible_hostname }}"
      path: /var/www/html/index.html

  - name: start httpd
    service: 
      name: "{{ service }}" 
      state: started  