---

  - name: "Create Test env label"
    illumio.core.label:
      key: env
      value: ANSIBLE
      state: present
      api_key_secret: "{{mykey_secret}}"
      api_key_username: "{{mykey_username}}"
      pce_hostname: "{{mypce_hostname}}"
      pce_port: 8443
      pce_org_id: 1 
    register: pce_label

  - debug: 
      var: pce_label

  - debug: 
      var: pce_label.label.href

  - name: Create pairing profile
    illumio.core.pairing_profile:
      name: PP-ANSIBLE
      enabled: true
      state: present
      api_key_secret: "{{mykey_secret}}"
      api_key_username: "{{mykey_username}}"
      pce_hostname: "{{mypce_hostname}}"
      pce_port: 8443
      pce_org_id: 1 
    register: profile_result

  - name: Generate pairing key
    illumio.core.pairing_key:
      api_key_secret: "{{mykey_secret}}"
      api_key_username: "{{mykey_username}}"
      pce_hostname: "{{mypce_hostname}}"
      pce_port: 8443
      pce_org_id: 1 
      pairing_profile_href: "{{ profile_result.pairing_profile['href'] }}"
    register: result

  - debug:
      var: result.pairing_key