--- # create a directory and copy files over with different permissions and ownership
- name: Hosts Playbook
  hosts: snc-public
  gather_facts: true
  tasks:

    - name: Print service
      ansible.builtin.debug:
        msg: package

    - name: Install service
      become: true
      ansible.builtin.package:
        name: "{{ package }}"
        state: latest

    - name: Create myindex.html file
      become: true
      ansible.builtin.file:
        name: /var/www/html/myindex.html
        state: touch

    - name: Add content to myindex file
      become: true
      ansible.builtin.lineinfile:
        line: "{{ inventory_hostname }}"
        line: "{{ hostvars[inventory_hostname]['ansible_facts'] }}"
        path: /var/www/html/myindex.html

    - name: Start service that you specify
      become: true
      ansible.builtin.service:
        name: "{{ package }}"
        state: started
